#!/bin/sh /etc/rc.common

START=95
STOP=95
USE_PROCD=1

start_service() {
	echo "Starting IPSSP Service..."
	procd_open_instance ipssp
	procd_set_param command /usr/sbin/ipssp -f -i wlan0-1 -r server -p 5951
	procd_set_param pidfile /var/run/ipssp.pid
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "ipssp"
	procd_add_interface_trigger "interface.*.up" wan /etc/init.d/ipssp reload
}

reload_service()
{
	stop
	start
}
